files/alembic.ini usr/share/securedrop-client/
files/client.ini usr/share/securedrop-client/
alembic/env.py usr/share/securedrop-client/alembic/
alembic/README usr/share/securedrop-client/alembic/
alembic/script.py.mako usr/share/securedrop-client/alembic/
alembic/versions/5344fc3a3d3f_add_user_table.py usr/share/securedrop-client/alembic/versions/
alembic/versions/fe7656c21eaa_add_remainder_of_database_models.py usr/share/securedrop-client/alembic/versions/
files/securedrop-client usr/bin/
