#!/bin/bash
# Wrapper script to create/update the requirements.txt
# It finds the correct project directory from the `PKG_DIR` envirionment variable.
#

set -e
set -u
set -o pipefail

if [[ -z "${PKG_DIR:-}" ]]; then
    echo "Set PKG_DIR of the project.";
    exit 1
fi

cd $PKG_DIR

# Now make a copy of the new requirements file.
# This will overwrite any previous build requirements if it exists,
# and in the next script we'll add in the hashes from FPF PyPI.
cp requirements.txt build-requirements.txt
