#!/bin/bash
# Utility script to generate a signed tag for the packaging repo:
#
#   https://github.com/freedomofpress/securedrop-builder
#
# Collects "version" field from package changelogs and prepares a summary
# commit message when incrementing the tag.
set -e
set -u
set -o pipefail


if [[ $# != 1 ]]; then
    echo "Usage: $0 <version>"
    packaging_curver="$(git tag | sort -V | tail -n1)"
    echo "The most recent tag available is: $packaging_curver"
    echo "You probably want to increment that with a new tag."
    exit 1
fi

new_version="$1"
printf 'securedrop-builder %s\n\n' "$new_version"
# Inspect all changelogs, prepare a pretty list of packages & versions
for pkg in securedrop-*; do
    pkg_version="$(dpkg-parsechangelog -SVersion --file "${pkg}/debian/changelog-buster" | perl -npE 's/\+buster$//')"
    printf '%s %s\n' "$pkg" "$pkg_version"
done
