#!/bin/bash

# This script uses the desktop-file-validate utility to lint .desktop files
# in this repository. See: https://www.freedesktop.org/wiki/Software/desktop-file-utils/

set -e
set -u
set -o pipefail

if ! [ -x "$(command -v desktop-file-validate)" ]; then
  echo "Error: desktop-file-validate is not installed. Run 'make install-deps'." >&2
  exit 1
fi

BASEDIR=$(dirname $0)
SEARCHDIR=$(realpath ${BASEDIR}/..)

# We can add additional excluded paths as needed, following the pattern below.
find ${SEARCHDIR} -name *.desktop -type f -not -path '*/\.git/*' | xargs desktop-file-validate
