#!/bin/bash

# A script to update the sha256sums from localwheels directory

set -e
set -u
set -o pipefail

cd ./localwheels/
sha256sum * > ../sha256sums.txt

printf "Now you must sign the generated sha256sums.txt file."
gpg --armor --output ../sha256sums.txt.asc --detach-sig  ../sha256sums.txt
