#!/bin/bash
# Wrapper script for `dch`, for editing changelogs in Debian packages.
# Provides flags on invocation, and also checks for env vars, so that
# maintainer info makes it into the package.
set -e
set -u
set -o pipefail

TOPLEVEL="$(git rev-parse --show-toplevel)"
VERSION_CODENAME=$("${TOPLEVEL}/scripts/codename")

# These env vars are only required when updating changelogs,
# otherwise the developer must edit the fields by hand, lest
# they commit "user@localhost" entries.
export DEBEMAIL=${DEBEMAIL:-"securedrop@freedom.press"}
export DEBFULLNAME=${DEBFULLNAME:-"SecureDrop Team"}

# Determine which package we want to update the changelog for.
# As with the other tools, we'll support the PKG_NAME env var.
PKG_NAME="${PKG_NAME:-}"
if [[ -z "${PKG_NAME:-}" ]]; then
    if [[ -n "${1:-}" ]]; then
        PKG_NAME="$1"
        shift
    else
        printf 'Usage: %s <package_name>\n' "$0"
        printf 'You can also export PKG_NAME\n'
        exit 2
    fi
fi

if [[ -z "${PKG_VERSION:-}" ]]; then
    echo "Error: cannot find env var PKG_VERSION."
    exit 3
fi


# Look for a changelog as d/changelog-$platform, d/changelog, or d/changelog-bullseye
if [[ -f "${TOPLEVEL}/${PKG_NAME}/debian/changelog-${VERSION_CODENAME}" ]]; then
    changelog="${TOPLEVEL}/${PKG_NAME}/debian/changelog-${VERSION_CODENAME}"
else
    if [[ -f "${TOPLEVEL}/${PKG_NAME}/debian/changelog" ]]; then
        changelog="${TOPLEVEL}/${PKG_NAME}/debian/changelog"
    else
        changelog="${TOPLEVEL}/${PKG_NAME}/debian/changelog-bullseye"
    fi
fi

dch -b --newversion "${PKG_VERSION}+${VERSION_CODENAME}" --distribution unstable -c "$changelog"
