---
name: CI

on: [merge_group, push, pull_request]

env:
  POETRY_VERSION: 2.1.3

jobs:
  checks:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - name: Bootstrap Debian system package dependencies
        run: |
          apt-get update && apt-get install --yes --no-install-recommends make sudo git git-lfs ca-certificates \
            pipx
          pipx install poetry==$POETRY_VERSION
          pipx ensurepath
          echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          lfs: true
      - name:  Install additional packages and Python dependencies
        run: |
          poetry install --no-ansi
      - name: Run linters
        run: |
          make lint
      - name: Run tests except reprotest
        run: |
          make test

  checksums:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - name: Bootstrap Debian system package dependencies
        run: |
          apt-get update && apt-get install --yes --no-install-recommends make git git-lfs gnupg ca-certificates
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          lfs: true
      - name: Verify checksums and signatures
        run: |
          git config --global --add safe.directory '*'
          ./scripts/verify-sha256sum-signature securedrop-client
          ./scripts/verify-sha256sum-signature securedrop-export
          ./scripts/verify-sha256sum-signature securedrop-log
          ./scripts/verify-sha256sum-signature workstation-bootstrap
