---
name: CI

on:
  merge_group:
  push:
  pull_request:
  schedule:
    - cron: "0 6 * * *"

jobs:
  reprotest:
    runs-on: ubuntu-latest
    container: debian:bookworm
    steps:
      - name: Bootstrap Debian system package dependencies
        run: |
          apt-get update && apt-get install --yes --no-install-recommends make sudo git git-lfs ca-certificates
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name:  Install additional packages and Python dependencies
        run: |
          # Installs Python & bootstrap wheels, and initializes a virtualenv at .venv
          make install-deps
          ./.venv/bin/pip install -r test-requirements.txt
      - name: Test wheel reproducibility
        run: |
          # Necessary to enable git operations without permission issues
          git config --global --add safe.directory "*"
          # Necessary to run checks as non-root user, to avoid reproducibility issues
          adduser --system ci --ingroup root
          chown ci:root -R .
          sudo -u ci bash -c "source .venv/bin/activate && pytest -vvs tests/test_reproducible_wheels.py"
